### ISSUE TITLE
mastercomfig MIT license

### ISSUE THREAD

**Issue by micwoj92** [m00n01/LunarConfig#7]
This repo contains assets from mastercomfig, but does not follow the attribution requirement within the MIT license in the mastercomfig repo. Please fix this, such that LunarConfig includes the copyright notice for mastercomfig within its own license.

**Comment by micwoj92** [comment]
see https://github.com/micwoj92/broconfig/issues/1 for more details

**Comment by m00n01** [comment]
Fixed. Thank you @micwoj92, you are my hero!
